### ISSUE TITLE
Running fire frequency

### ISSUE THREAD

**Issue by petebrew** [petebrew/fhaes#107]
Chris Guiterman has requested that we support the output of running fire frequency.  This is available in FHX2 but missing from FHAES.

**Comment by eksutherland** [comment]
Can he or someone reference it in Henri’s FHX manual? His current one.

**Comment by eksutherland** [comment]
Peter, how did your conferences about FHAES go?

**Comment by petebrew** [comment]
Duplicate of bug #20
