### ISSUE TITLE
The order of values in the seasonality summary table need to be re-arranged

### ISSUE THREAD

**Issue by eksutherland** [petebrew/fhaes#116]
[I've assigned this to Peter but maybe it should go to Elena.]

I've just realized that the seasonality values are not logically arranged in the summary table and are rather confusing.  This is not an emergency but if rearranging them is an easy fix, I would appreciate it.  I attach some files that should be helpful in explaining how the table should be arranged.  Look on page 23 of the Swetnam & Baison 1994 paper for a helpful figure.  In general, the order should be E,M, L, A, D if A and D are grouped together or D,E,M,L,A if D and E are grouped together (see explanations in the Arrangement Seasonality Table pdf, attached.)

[Arrangement Seasonality Table.pdf](https://github.com/petebrew/fhaes/files/9751/Arrangement.Seasonality.Table.pdf)
[Swetnam_Baisan_1996_RM-GTR-289_madreanborderlands.pdf](https://github.com/petebrew/fhaes/files/9755/Swetnam_Baisan_1996_RM-GTR-289_madreanborderlands.pdf)

**Comment by petebrew** [comment]
The table is sorted into alphabetical order!  The raw table produced by Elena's code looks like this:
![screeny](https://cloud.githubusercontent.com/assets/768597/10358757/7a8d9860-6d46-11e5-85b3-e760bb8e8465.png)

Reordering in the code would be possible but a little tedious.  If you can confirm the precise order you'd prefer then I'll see what I can do.

**Comment by eksutherland** [comment]
Ok. It's not a super high priority need but I realized I was struggling to sort the values into their correct groups. I just wanted to capture the issue while it was fresh in my mind.


Elaine Kennedy Sutherland, PhD

Supervisory Research Biologist &

Scientist in Charge, Coram Experimental Forest



Forest Service, Rocky Mountain Research Station

Desk: 406-542-4169

Cell: 406-370-0164

esutherland@fs.fed.us<mailto:esutherland@fs.fed.us>



Forestry Sciences Laboratory

800 E. Beckwith Avenue, Missoula, MT 59801

www.fs.fed.us<http://www.fs.fed.us>



Caring for the land and serving people


-----Original Message-----

**Comment by eksutherland** [comment]
Note the Swetnam and Baisan paper I attached in the original message.

Tree rings grow in the following way:
Earlywood then Latewood

For these purposes earlywood can be divided into 3 categories:
EE = Early Earlywood = First third of the earlywood
ME= Middle-Earlywood = Second third of the earlywood
LE = Late-Earlywood = Last third of the earlywood
A = Latewood
And D = between rings or Dormant (growth) season

When the margin of the scar can be followed into a ring or between rings then season can be assigned.
Otherwise the season is Unknown = U.

This defines the seasonality ordering.  Wildfire seasons vary from region to region.  In the Southwest, it is in May and June, before growth begins or during the Earlywood (see Figure 3 from Swetnam and Baisan 1996, below) – where dormant season fires are in the early spring.

In the Pacific Northwest, wildfire season doesn’t start until mid-July when the growing season is drawing to a close, so the scar is in the latewood or between rings (A or D) where dormant season fires are in the late summer or early autumn.

Thus you can see that in a PERFECT world, the order of the table could go two ways depending on how the user has chosen groups.

For the Southwest the user’s hypothesis would be that there are more Dormant Season and Early fires than Late fires.  The user would form two groups:  D+EE+ME vs. LE+A and maybe do a chi-square analysis to test the hypothesis [which is something else we need to add :-0 ]

In that case the perfect summary table would be listed as D, EE, ME, LE, A (number) and then same for percentage.

For the Pacific Northwest the user’s hypothesis would be that there are fewer spring and early summer fires compared to late and dormant season fires.  The user’s groups would be EE+ME+LE vs. A+D.

The summary table lineup would be EE, ME, LE, A, D.

IN AN IMPERFECT WORLD
The order should be EE, ME, LE, A, D.



Figure 3. From Swetnam & Baisan 1996.  GTR-RM-289 Madrean Borderlands.
[cid:image001.png@01D101C6.D2C4A4B0]

**Comment by petebrew** [comment]
How about this for now?

![screeny](https://cloud.githubusercontent.com/assets/768597/10376805/bf1eae38-6db4-11e5-9e48-a88deb5cfb79.png)

The seasonality groups are labeled with seasons in the order DEMLA.  Therefore in your Southwest scenario (as in the screeny) the labels will be DEM and LA.  However in your Pacific Northwest the groups will be EML and DA rather than AD.  Working out the logical order of these wouldn't be trivial especially as we currently have no restrictions for nonsensical groups e.g. DMA and EL.

**Comment by eksutherland** [comment]
That’s great, Peter.  The total number within groups is what matters, not the order of letters within groups.  This is entirely satisfactory.
