### ISSUE TITLE
File summaries of files without recording years are blank

### ISSUE THREAD

**Issue by eksutherland** [petebrew/fhaes#133]
If fhx files do not have recording years indicated then the file summaries are blank.  See file uslytl001.fhx, attached.

**Comment by lunavelasquez** [comment]
Yes.

I am aware of that.

Elena

**Comment by eksutherland** [comment]
I know – it was a notification to Peter ….. you were just copied on it…..

**Comment by petebrew** [comment]
The file uslytl001 has an error in it.  If a file has an error it cannot be processed and therefore a summary cannot be created.  Files that are valid but have no recording/event years are handled correctly and a summary is produced.
